name: CD Back-and

on:
  workflow_dispatch:

jobs:

  ci:
    name: CI workflow Main
    uses: ./.github/workflows/ci-backend.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Deploy
        uses: johnbeynon/render-deploy-action@master
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-sucess: true